# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GH Release'
description: 'Github Action for creating Github Releases'
author: 'spaceface777'
inputs:
  run_if:
    description: 'Whether to actually run this action. Defaults to true'
    required: false
  body:
    description: 'Note-worthy description of changes in release'
    required: false
  body_path:
    description: 'Path to load note-worthy description of changes in release from'
    required: false
  name:
    description: 'Gives the release a custom name. Defaults to tag name'
    required: false
  tag_name:
    description: 'Gives a tag name. Defaults to github.GITHUB_REF'
    required: false
  draft:
    description: 'Creates a draft release. Defaults to false'
    required: false
  prerelease:
    description: 'Identify the release as a prerelease. Defaults to false'
    required: false
  files:
    description: 'Newline-delimited list of path globs for asset files to upload'
    required: false
  filename:
    description: 'What to name the uploaded asset'
    required: false
  overwrite:
    description: 'Whether to overwrite existing tags and releases'
    required: false
  create_zip:
    description: 'Whether to create a zip archive out of the given input files'
    required: false
  attach_only:
    description: 'Whether to only attach files, and error if the release does not exist'
    required: false
  attach_only:
    description: 'Whether to only create the release, and not attach any files to it'
    required: false
  fail_on_unmatched_files:
    description: 'Fails if any of the `files` globs match nothing. Defaults to false'
    required: false
env:
  'GITHUB_TOKEN': 'As provided by Github Actions'
outputs:
  url:
    description: 'URL to the Release HTML Page'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'package'